### ISSUE TITLE
Update to 1.19?

### ISSUE THREAD

**Issue by jacobjake1** [rob9315/mcproxy#25]
Hey, since 2b2t just updated from 1.12.2 to 1.19 I was wondering if you had plans/if you are able to update this to 1.19 as I have this as a dependency for my project? Thanks

**Comment by rob9315** [comment]
sorry i have no interest in further developing this project, take a look at the fork from @IceTank for new features and probably at some point new versions

**Comment by IceTank** [comment]
Yes, my fork of mcproxy has a working 1.19 branch. But, not all features have been implemented yet, and there are still some issues. Once all issues have been resolved, I will make a new mcproxy release under my name space.
