### ISSUE TITLE
Crashing after reconnecting too many times

### ISSUE THREAD

**Issue by rob9315** [rob9315/mcproxy#3]
(originally by @MrGeorgen)
> themoonisacheese/2bored2wait#269

[answer by @rob9315]
> Needs a try statement somewhere to prevent crashing with (incomplete packets?)

[answer by @MrGeorgen]
> https://github.com/rob9315/mcproxy/blob/be18df0cbea6b42544ec2675948127a46fe54431/src/conn.ts#L119
> this is the line the error belongs to. However should not `bot.entity` always
be defined? And if it is not, I guess there is not really a way to send the
client proper data.

[answer by @rob9315]
> It should always be defined, but it seems that when you call it too early or the client is being declined, it crashes. I think there needs to be a check in place to determine if the client isn't being declined, which I think is the case. (Or one try statement around sendPackets)

**Comment by Ashesh3** [comment]
Hey, I've been having the exact same issue. crashed at that same line.

```

6|2b2w     | TypeError: Cannot read property 'id' of undefined
6|2b2w     |     at Conn.generatePackets (/root/2bored2wait/node_modules/@rob9315/mcproxy/lib/conn.js:104:43)
6|2b2w     |     at Conn.sendPackets (/root/2bored2wait/node_modules/@rob9315/mcproxy/lib/conn.js:93:28)
6|2b2w     |     at /root/2bored2wait/main.js:327:9
6|2b2w     |     at runMicrotasks (<anonymous>)
6|2b2w     |     at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

The line

```
              entityId: this.bot.entity.id,
```

Happened totally randomly while exploring the world.

**Comment by rob9315** [comment]
This really should only happen when someone tries to connect to the proxy. The method is only called upon generating Packets. The method should only be called when the bot is ready, there is a test missing in 2b2w. Though this can probably be fixed with a similar check inside the library.

I will fix this later today

**Comment by rob9315** [comment]
Fixed with latest commit
